---
 - name: update cache
   apt:
     update_cache: yes
 - name: install nginx
   apt:
     name: "nginx"
     state: latest
   notify:
    - NGINX started
 - name: copy usual nginx conf
   template:
     src: nginx.conf
     dest: /etc/nginx/nginx.conf
 - name: template for nginx
   template:
     src: nginx-balancer-config.conf
     dest: /etc/nginx/conf.d/
   notify: new nginx config
