---
 - name: add group minio-user
   group:
    name: minio-user
    state: present
 - name: Add a system account for minio
   user:
     name: minio-user
     shell: /usr/sbin/nologin
     expires: 33333333
     group: minio-user
 - name: download minio from source
   get_url:
     url: https://dl.min.io/server/minio/release/linux-amd64/minio
     dest: /usr/local/bin
     mode: '0777'
     owner: minio-user
     group: minio-user
 - name: Create a share 
   file:
     path: /usr/local/share
     state: directory
     mode: '0755'
     owner: minio-user
     group: minio-user
 - name: Create a config directory
   file:
    path: /etc/minio
    state: directory
    mode: '0755'
    owner: minio-user
    group: minio-user
 - name: copy config file
   copy:
     src: /home/xisen/iq-option/roles/minio/templates/minio
     dest: /etc/default
 - name: copy config file
   copy:
     src: /home/xisen/iq-option/roles/minio/minio.service
     dest: /etc/systemd/system


 - name: copy tokens
   copy:
     src: /home/xisen/iq-option/roles/minio/templates/export_env
     dest: /opt/
 - name: export_env
   shell: cat /opt/export_env >> /etc/environment
 - name: restart systemctl
   command: systemctl daemon-reload
   notify: minio service installed

# - name: run minio
#   command: /usr/local/bin/minio server /data 
 - name: allow 9000
   ufw:
     rule: allow
     port: 9000:9010
     proto: tcp
   notify: ufw installed 

