---
 - name: add group minio-user
   group:
    name: minio-user
    state: present
 - name: Add a system account for minio
   user:
     name: minio-user
     shell: /usr/sbin/nologin
     expires: 55555555555
     group: minio-user
 - name: Create a share
   file:
     path: "{{ item }}"
     state: directory
     mode: '0755'
     owner: minio-user
     group: minio-user
   with_items: "{{ folders }}"
# - name: Create a share
#   file:
#     path: "{{ folder1 }}"
#     state: directory
#     mode: '0755'
#     owner: minio-user
#     group: minio-user
#   loop: 
#     - "{{ folders }}"
# - name: Create a share
#   file:
#     path: "{{ folder2 }}"
#     state: directory
#     mode: '0755'
#     owner: minio-user
#     group: minio-user
 - name: download minio from source
   get_url:
     url: https://dl.min.io/server/minio/release/linux-amd64/minio
     dest: /usr/local/bin
     mode: '0777'
     owner: minio-user
     group: minio-user
 - name: Create a share 
   file:
     path: /usr/local/share
     state: directory
     mode: '0755'
     owner: minio-user
     group: minio-user
 - name: Create a config directory
   file:
    path: /etc/minio
    state: directory
    mode: '0755'
    owner: minio-user
    group: minio-user
 - name: copy config file
   copy:
     src: minio_token
     dest: /etc/default/minio
 - name: copy config file
   template:
     src: minio.service
     dest: /etc/systemd/system
 - name: create a first backet
   file:
     path: "{{ item }}/bucket"
     state: directory
     mode: '0755'
     owner: minio-user
     group: minio-user
   with_items: "{{ folders }}"
# - name: export_env
#   shell: cat /opt/export_env >> /etc/environment
 - name: restart systemctl
   command: systemctl daemon-reload
   notify: minio service installed
